#SPDX-License-Identifier: MIT-0
---
- name: "Install packages"
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: latest
    #upgrade: yes
    aur_only: false
    update_cache: true
    use: yay
  become: false
  loop:
    - git
    - make
    - nodejs
    - rust
    - ripgrep
    - npm
    - lazygit
- name: Install packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: latest
    #upgrade: yes
    aur_only: false
    update_cache: true
    use: yay
  become: false
  loop:
    - lunarvim-git
- name: "Install lvim config"
  ansible.builtin.include_role:
    name: symlink
  loop: "{{ file_list }}"
