---
- name: DEBUG
  debug:
    msg: 
    - "Source: {{ item.src }}"
    - "Destination: {{ item.dest }}"
- name: Check if symlink path exists
  ansible.builtin.stat:
    path: "{{ item.dest }}"
  register: symlink_stat
- name: Backup existing file
  ansible.builtin.command:
    cmd: mv "{{ item.dest }}" "{{ item.dest }}.bak"
  when: symlink_stat.stat.exists
- name: Notify backup creation
  ansible.builtin.debug:
    msg: "Backup created for {{ item.dest }}"
  when: symlink_stat.stat.exists
- name: Notify no backup needed
  ansible.builtin.debug:
    msg: "Backup not created because file or folder {{ item.dest }} doesn't exist"
  when: not symlink_stat.stat.exists
- name: Create symbolic link
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
