[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black   = "#000000"
red     = "#cd3131"
green   = "#0dbc79"
yellow  = "#e0af68"
blue    = "#2472c8"
magenta = "#bc3fbc"
cyan    = "#11a8cd"
white   = "#e5e5e5"

[colors.bright]
black   = "#666666"
red     = "#f14c4c"
green   = "#23d18b"
yellow  = "#ff9e64"
blue    = "#3b8eea"
magenta = "#d670d6"
cyan    = "#29b8db"
white   = "#e5e5e5"

[colors.primary]
background = "#0d0d0f"
foreground = "#d4d4d4"

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "CaskaydiaCove NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CaskaydiaCove NFM"
style = "Italic"

[font.normal]
family = "CaskaydiaCove NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"


[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.80
# Maximized
startup_mode = "Fullscreen"

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true

[terminal]
