#SPDX-License-Identifier: MIT-0
---
- name: Install packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: latest
    upgrade: yes
    use: yay
  loop:
    - gitui
- name: Install gitui config
  ansible.builtin.include_role:
    name: symlink
  loop: "{{ file_list }}"
