#SPDX-License-Identifier: MIT-0
---
- name: Install packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: latest
    #upgrade: yes
    aur_only: false
    update_cache: true
    use: yay
  become: false
  loop:
    - tmux
- name: "Clone tmux plugin manager (tpm)"
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '{{ linux_home }}/.tmux/plugins/tpm'
    clone: yes
    update: yes
- name: Install tmux config
  ansible.builtin.include_role:
    name: symlink
  loop: "{{ file_list }}"
