#SPDX-License-Identifier: MIT-0
---
- name: "Create `alacritty` directory if it doesn't exist"
  ansible.builtin.file:
    path: "{{ linux_home }}/.config/alacritty"
    state: directory
    mode: '0755'
    owner: "{{ linux_user }}"
    group: "{{ linux_user }}"
- name: Install tmux config
  ansible.builtin.include_tasks: process_file.yaml
  loop: "{{ file_list }}"
