- name: Machine setup
  hosts: localhost
  become: true
  connection: local
  gather_facts: true
  collections:
    - kewlfft.aur
  vars:
    linux_distribution: "{{ ansible_distribution | lower }}"
    linux_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
    linux_home: "{{ ansible_env.HOME or ansible_env.SUDO_HOME }}"

  tasks:
    - name: Show variables
      debug:
        msg: 
          - "Distrib : {{ linux_distribution }}"
          - "User : {{ linux_user }}"
          - "Home : {{ linux_home }}"
