- name: Deploying dotfiles
  hosts: localhost
  become: true
  connection: local
  gather_facts: true
  collections:
    - kewlfft.aur
  vars:
    linux_distribution: "{{ ansible_distribution | lower }}"
    linux_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
  tasks:
    - name: Show variables
      debug:
        msg: "{{ item }}"
      loop:
        - "{{ linux_distribution }}"
        - "{{ linux_user }}"
