- name: Machine setup
  hosts: localhost
  become: true
  connection: local
  gather_facts: true
  collections:
    - kewlfft.aur
  vars:
    linux_distribution: "{{ ansible_distribution | lower }}"
    linux_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
  tasks:
    - name: "Update the system using pacman -Syuu"
      community.general.pacman:
        update_cache: true      # -Sy
        upgrade: true           # -u (upgrade all packages)
        # noconfirm: true         # --noconfirm (skip prompts)
        # force: true           # -uu (allow downgrades if needed)
    - name: "Install base-devel and git (required for AUR builds)"
      ansible.builtin.pacman:
        name:
          - base-devel
          - git
        state: present
    - name: "Install packages"
      kewlfft.aur.aur:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - xsel
        - wl-clipboard
        # - xclip
        - ctop
        - nvtop
        - eza
        - bat
        - vlc
        - ranger
        - gitui
        - gparted
        - firefox
        - steam
        - discord
        - signal-desktop
        - vscodium
        - obsidian
        - youtube-music
        - thunderbird
        - brave-bin
        - kdenlive
        - bitwarden
        - kdeconnect
        - timeshift
        # - rofi
        # - polybar 
        # - i3
    - name: "Install AUR packages"
      kewlfft.aur.aur:
        name: "{{ item }}"
        upgrade: false
        update_cache: false
        use: yay
        aur_only: true
        state: latest
      # can't install AUR packages as root
      become: false
      loop:
        - firefox-profile-switcher-connector-bin
        - deezer-enhanced-bin
        - deemix-git
        - video-downloader
