- name: Install dotfiles
  hosts: localhost
  become: true
  connection: local
  gather_facts: true
  tasks:
    - name: "Include roles"
      include_role:
        name: "{{ dotfiles_name }}"
      loop: "{{ mydotfiles }}"
      loop_control:
        loop_var: dotfiles_name
